---
- name: 웹서버 중지, 삭제
  hosts: all
  become: true

  tasks:
    - name: httpd stop
      service: name=httpd state=stopped
      when: ansible_distribution == 'Amazon'

    - name: httpd remove
      action: "{{ ansible_pkg_mgr}} name=httpd state=absent"
      when: ansible_distribution == 'Amazon'

    - name: nginx stop
      service: name=nginx state=stopped
      when: ansible_distribution == 'Ubuntu'

    - name: nginx remove
      action: "{{ ansible_pkg_mgr}} name=nginx state=absent autoremove=yes purge=yes"
      when: ansible_distribution == 'Ubuntu'
  
     
 









